Vagrant.configure(2) do |config|
  config.vm.box = "bento/fedora-24"
  config.vm.hostname = "ansible_host"
  config.vm.provision "shell", path: "provision.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 2048
    vb.name = "ansible_host"
    vb.customize ["modifyvm", :id, "--natnet1", "192.168.255.0/24"]
  end
end
